spring.application.name=fadex-barberia-backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate



jwt.secret=${JWT_SECRET}
jwt.expiration=9000000
logging.level.org.flywaydb=DEBUG


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=15MB

server.tomcat.max-http-form-post-size=15MB
server.tomcat.max-swallow-size=15MB

app.upload.max-size=5

#gmal del negocio por si quieren entrar
#barberiafadex@gmail.com
#vjfa nsyh qsqn ahgx
#contrse�a FadexBarberia123


gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

file.upload-dir=uploads/

server.port=${PORT:8081}

ia.microservicio.url=${IA_URL}

logging.level.com.sistemabarberia=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=ERROR
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE